apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.1
  - resources/namespace.yaml

patches:
  - path: patches/argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm

  - path: patches/argocd-repo-server-deployment.yaml
    target:
      kind: Deployment
      name: argocd-repo-server

  - path: patches/argocd-server-deployment.yaml
    target:
      kind: Deployment
      name: argocd-server
