apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.1
  - resources/namespace.yaml

patchesStrategicMerge:
  - patches/argocd-cm.yaml
